### ISSUE TITLE
Core dump and keyboard not working anymore

### ISSUE THREAD

**Issue by pmontrasio** [rokyed/power-touch#3]
This is an Ubuntu 16.04 with Gnome Flashback and Compiz.

I played with the app for a few minutes until I got a core dump.

After that I couldn't type anything anymore in the terminal windows. It seems that every key is a return. Every tab is affected. Running another terminal from the Applications menu didn't help, possibly because it's the same process. Even ALT-F2 didn't work to open the app launcher menu.

I closed all the terminal tabs, run another terminal and I can type again.

Unfortunately the core dump didn't create a core file.

**Comment by rokyed** [comment]
hmm, i expect that comes from robotJS

**Comment by rokyed** [comment]
please can you try it again see if you get the core dump, is not supposed since i am not using anymore exec, i changed it for spawn, unless the core dump comes from robotjs
